{
 "title": "APC UPS Detailed Summary",
 "description": "A Flux-based modification of the InfluxQL-based dashboard from https://grafana.com/grafana/dashboards/12625 - thank you, jenniferhatches.  Modifications pertain to layout (less emphasis on power consumption costs), colour thresholds for UPS Runtime, and the addition of power factor calculated based on maximum load/real power (watts) and maximum apparent power (volt-amps) supported by the UPS, as well as correct representation of the calculated load and total UPS consumption as a function of load percentage. You will need to manually alter the load power figures for the \"maxwatt\" variable, in accordance with APC's official specifications for your UPS unit(s). \"maxvoltamp\" variable will continue to automatically extract its value from the model name, as per the previous author's design.\n\nNotes for Revision 2: Completely revamped the calculation for kWh graphs, which were so far away from accuracy I'm embarrassed I overlooked them when interpreting the code from InfluxQL to Flux. Correctly using integral function for gathering kWh consumption in both 24hr and 1M periods.",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "upsdatasource", "label": "UPS Datasource", "query": "influxdb" },
   {
    "name": "upsname",
    "label": "UPS Name",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\")\r\n  |> keep(columns: [\"ups_name\"])\r\n  |> group()\r\n  |> distinct(column: \"ups_name\")\r\n\r\n  "
   },
   {
    "name": "maxvoltamp",
    "label": "UPS Max Output Power Capacity (VA)",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> keep(columns: [\"model\"])\r\n  |> group()\r\n  |> distinct(column: \"model\")\r\n\r\n"
   },
   {
    "name": "maxwatt",
    "label": "UPS Max Output Power Capacity (W)",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"nominal_power\")\r\n  |> keep(columns: [\"_time\",\"ups_name\"])\r\n  |> map(fn: (r) => ({ r with _value: if \"${upsname}\" == \"UPSTower\" then 800 else 980}))\r\n  |> yield(name: \"last\")\r\n"
   },
   {
    "name": "powerfactor",
    "label": "Power Factor",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> keep(columns: [\"_time\",\"ups_name\"])\r\n  |> map(fn: (r) => ({ r with _value: if \"${upsname}\" == \"UPSTower\" then float(v: ${maxwatt})/float(v: ${maxvoltamp}) else float(v: ${maxwatt})/float(v: ${maxvoltamp})}))\r\n  |> yield(name: \"last\")\r\n"
   },
   { "name": "kwhprice", "label": "kWh Price", "query": ".15" },
   { "name": "currency", "label": "Currency", "query": "$,€,£,C$,kr,₽,¥,R" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> keep(columns: [\"status\"])\r\n  |> group()\r\n  |> distinct(column: \"status\")\r\n  |> last()\r\n  ",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Load Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"load_percent\")\r\n  |> group()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"battery_charge_percent\")\r\n  |> group()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"time_left_ns\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"time_on_battery_ns\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"battery_voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Current UPS Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> map(fn: (r) => ({ r with _value: (r._value / 100.0) * float(v: ${maxwatt})}))\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100*$maxwatt" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> map(fn: (r) => ({ r with _value: (r._value / 100.0) * float(v: ${maxvoltamp})}))\r\n  |> keep(columns: [\"_value\"])\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Runtime Remaining",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Runtime Remaining",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"time_left_ns\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"battery_charge_percent\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "time_left_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"input_voltage\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"input_voltage\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Hz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"input_frequency\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "input_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"input_voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charge %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"battery_charge_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"battery_charge_percent\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "UPS Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"load_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"battery_charge_percent\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"output_voltage\")\r\n  |> last()\r\n  |> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Internal Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"internal_temp\")\r\n  |> last()\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "internal_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"battery_voltage\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"battery_voltage\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"input_frequency\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"input_frequency\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Day's Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"load_percent\"])\r\n  |> map(fn: (r) => ({ r with _value: ((r._value / 100.0) * float(v: ${maxvoltamp}) / 1000.0)}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Past Day's Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Costs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> map(fn: (r) => ({ r with _value: ((r._value / 100.0) * float(v: ${maxvoltamp}) / 1000.0) * ${kwhprice}}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*$kwhprice" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"time_on_battery_ns\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"time_on_battery_ns\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\")\r\n  |> filter(fn: (r) => r._field == \"output_voltage\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"output_voltage\",\"upsname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "battery_charge_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> aggregateWindow(\r\n    every: 1h,\r\n    fn: (tables=<-, column) =>\r\n        tables\r\n            |> integral(unit: 1h)\r\n            |> map(fn: (r) => ({ r with _value: ((r._value / 100.0) * float(v: ${maxvoltamp}) / 1000.0)})))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "apcupsd",
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"apcupsd\" and r.ups_name == \"${upsname}\" and r._field == \"load_percent\")\r\n  |> aggregateWindow(\r\n    every: 1h,\r\n    fn: (tables=<-, column) =>\r\n        tables\r\n            |> integral(unit: 1h)\r\n            |> map(fn: (r) => ({ r with _value: ((r._value / 100.0) * float(v: ${maxvoltamp}) / 1000.0)})))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n//  |> keep(columns: [\"_time\",\"_value\",\"upsname\"])\r\n//  |> map(fn: (r) => ({ r with _value: ((r._value / 100.0) * float(v: ${maxvoltamp}) / 1000.0 * 24.0)}))\r\n//  |> keep(columns: [\"_time\",\"_value\"])\r\n//  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n//  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "load_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*$maxwatt/1000*24" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ups_name", "operator": "=~", "value": "/^$upsname$/" }
     ]
    }
   ]
  }
 ]
}